# Probability


In [ ]:
likelihood of an event to occur,

0 to 1

p(A) = number of desired outcome/number of all outcomes

example - roll a die, the probability of getting a number less than 3

p(A) = 2/6

# Conditional Probability

<img src='n1.png' />

In [ ]:
likelihood of an event to occur given that 
another event that has a relation with event A has already occured


A - event of picking up the blue ball
B - condition that you have to pick the ball from box A

p(A|B)

## Joint Probability

In [ ]:
two events are occuring together

p(A and B) = p(A).p(B)

In [ ]:
p(roll a die and coin toss) = 1/6 . 1/2 = 1/12 = 0.08

p(frequency of the word FREE and the word won) = 12/140 . 2/140 = 24/19600 = spam or ham (email)

                                                                   0.001    0 - 0.5  0.5 - 1

In [ ]:
52 card in a deck

1/52

events are dependent

In [ ]:
p(A and B) = p(A).p(B|A)   - for dependent events

# Bayes Theorem

<img src='n2.png' />

In [ ]:
probability of an event happening related to any condition

- probability of causes

# Naive Bayes Classifier

In [ ]:
Naive - it assumes that the features are independent to each other

Bayes - Bayes theorem(Thomas Bayes)

In [ ]:
- classification


In [ ]:
real world examples

- text classification
    - email spam filter
    - sentiment analysis
    - document categorization
    - user review analysis
- credit scoring
- autonomous vehicles collision avoidance
    - likelihood of a collision given the current sensor data



In [ ]:
Gaussian NB    - continuous data, features are normally distributed
Multinomial NB - discrete data, counts or frequencies
Bernoulli NB   - binary or discrete data, assumes bernoulli distribution

### iris dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

# iris

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
from sklearn.naive_bayes import GaussianNB

gb = GaussianNB()

gb.fit(df, iris.target)

GaussianNB()

In [7]:
gb.score(df, iris.target)

0.96

In [8]:
gb.predict([[5.1,3.5,1.4,0.2]])

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0])

In [10]:
docs = pd.read_table('SMSSpamCollection+(1)', header=None, names=['Class', 'SMS'])

docs.head()

Class                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
docs.Class.value_counts()

ham     4825
spam     747
Name: Class, dtype: int64

In [12]:
docs['label'] = docs.Class.map({'ham': 0, 'spam': 1})

docs.head()

Class                                                SMS  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [13]:
x = docs.SMS
y = docs.label

print(x.shape)
print(y.shape)

(5572,)
(5572,)


In [14]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest  =train_test_split(x,y, random_state=101)

In [15]:
xtrain.head()

1851    Then cant get da laptop? My matric card wif ü ...
3280    Solve d Case : A Man Was Found Murdered On  &l...
3426                      True. Its easier with her here.
111              What is the plural of the noun research?
3788                          WHORE YOU ARE UNBELIEVABLE.
Name: SMS, dtype: object

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vector = CountVectorizer(stop_words='english')

vector.fit(xtrain)

CountVectorizer(stop_words='english')

In [17]:
xtrain_transformed = vector.transform(xtrain)
xtest_transformed = vector.transform(xtest)

In [18]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(xtrain_transformed, ytrain)

ypred_class = mnb.predict(xtest_transformed)

ypred_proba = mnb.predict_proba(xtest_transformed)

In [20]:
from sklearn.metrics import accuracy_score

accuracy_score(ytest, ypred_class)

0.9849246231155779

In [21]:
ypred_class

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import confusion_matrix

confusion_matrix(ytest, ypred_class)

array([[1219,    8],
       [  13,  153]], dtype=int64)

## Quick Tips

In [ ]:
- Naive bayes algorithm assumes that the features are independent of each other

- it can be trained faster than other algorithms

- the NB model can predict faster as compared to other algorithms

- serialization is smooth in NB

- it does not involve optimization of a cost function

## Dataset to work on

https://www.kaggle.com/code/prashant111/naive-bayes-classifier-in-python/notebook