# NumPy

Numeric Python

In [ ]:
list  - collection of different type of elements
array - collection of similar type of elements

In [1]:
!pip install numpy

### 1 - Creating a vector

In [1]:
import numpy as np

In [5]:
# help(np.array)

In [6]:
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [7]:
print(type(v))

<class 'numpy.ndarray'>


In [8]:
v = np.array([[1],[2],[3]])

v

array([[1],
       [2],
       [3]])

### 2 - Matrix

In [9]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension ----->    .
1st dimension ----->    ._________.   # number line

2nd dimension ----->    .____|_____.

3rd dimension ----->    ._____|_____.
                             /

4th dimension ----->
.
.
.
nth dimensions

In [ ]:
# what is the real world example of linear algebra (matrix)
1080p

720p

### 3 - Describe Matrix

In [2]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matrix.shape

(3, 3)

In [13]:
matrix.size

9

In [14]:
matrix.ndim

2

### 4 - Max and Min Values

In [3]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(np.max(matrix))

9


In [5]:
print(np.min(matrix))

1


In [6]:
print(np.max(matrix, axis=0))  # columns

[7 8 9]


In [7]:
print(np.max(matrix, axis=1)) # rows

[3 6 9]


In [8]:
print(np.max(matrix, axis=1)[0]) # rows

3


### 5 - Statistics

In [ ]:
1. Descriptive -> Mean, Median, Mode, Standard Deviation, Variance, IQR, Percentile

2. Inferential -> models, hypothesis testing, regression(relationship)

In [18]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print(np.mean(matrix))

5.0


In [21]:
print(np.std(matrix))

2.581988897471611


In [22]:
print(np.var(matrix))

6.666666666666667


### 6 - Reshaping arrays

In [23]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print(matrix.reshape(9))

[1 2 3 4 5 6 7 8 9]


In [25]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [26]:
print(matrix.reshape(9,2))

ValueError: cannot reshape array of size 9 into shape (9,2)

In [27]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


In [ ]:
## Assignment
Folder - Numpy books

solve chapters
3, 4, 5

# NumPy Part 2


## 7 - Selecting Elements

In [9]:
#            -7  -6 -5 -4  -3 -2  -1
v = np.array([11,12,13,14,15,16,17])
#             0  1  2  3  4  5  6

print(v[0])

11


In [10]:
print(v[5])

16


In [11]:
print(type(v))

<class 'numpy.ndarray'>


In [12]:
print(v[-1])

17


In [13]:
print(v[6])

17


In [14]:
# v[start : end]

#            -7  -6 -5 -4  -3 -2  -1
v = np.array([11,12,13,14,15,16,17])
#             0  1  2  3  4  5  6

print(v[3:6])

[14 15 16]


In [15]:
print(v[2:5])

[13 14 15]


In [16]:
print(v[0:])

[11 12 13 14 15 16 17]


In [18]:
print(v[0:-7])

[]


In [19]:
print(v[0:-4])

[11 12 13]


In [17]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
00  01  02
10  11  12
20  21  22

In [20]:
matrix[0,0]

1

In [21]:
matrix[2,1]

8

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matrix[: , 2:3]

array([[3],
       [6],
       [9]])

In [24]:
matrix[:, 2:2]

array([], shape=(3, 0), dtype=int32)

In [25]:
matrix[0:3 , 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 8 - Transpose of a matrix

In [26]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## 9 - Diagonal

In [28]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(matrix.diagonal())

[1 5 9]


In [30]:
print(matrix.diagonal(offset=1))

[2 6]


In [31]:
print(matrix.diagonal(offset=2))

[3]


In [32]:
print(matrix.diagonal(offset=-1))

[4 8]


In [33]:
print(matrix.diagonal(offset=-2))

[7]


In [34]:
np.diag(np.rot90(matrix))

array([3, 5, 7])

In [35]:
# some examples other than flipping an image

## 10 - Dot Product

In [36]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(np.dot(matrix1, matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
1*1 + 2*4 + 3*7

In [40]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1,2,3,4], [4,5,6,4], [7,8,9,4]])

print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]


In [41]:
print(np.dot(matrix1, matrix2))

[[ 30  36  42  24]
 [ 66  81  96  60]
 [102 126 150  96]]


## 11 - cross product

In [42]:
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix1 * matrix2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [43]:
print(np.add(matrix1, matrix2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [44]:
print(np.subtract(matrix1, matrix2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [45]:
print(np.divide(matrix1, matrix2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 12 - Random Values

In [50]:
np.random.randint(0,11,5)

array([6, 8, 8, 4, 9])

In [51]:
np.random.randint(0,11,9)

array([ 0,  1,  4,  1,  5,  9, 10,  5, 10])

In [55]:
np.random.randint(0,11,9).reshape(3,3)

array([[ 8,  6,  7],
       [ 8,  9,  4],
       [ 6, 10,  6]])

In [58]:
np.random.seed(5)

np.random.randint(0,11,3)

array([3, 6, 6])

In [59]:
np.random.normal(1.0, 2.0, 10)

array([ 0.95339251,  2.68355533,  3.73517105,  2.14941538, -2.77152482,
        1.34185074,  0.19381338,  4.27525698, -0.2105957 , -2.18883015])

In [ ]:
int -> 2 bytes

array 10 -> 20 bytes

 0      1     2
2011  2013  2015

In [ ]:
l = [1,2,3,4, "Him"]
    
    0
l = [1111, ]

1-> id 1111