# MLOps 

<img src='mlopss.png' />

<img src='mlflow.jpg' />

# Serialization of ML Models

In [ ]:
save model memory so that you can use it later

- json
- pickle
- joblib



# Building the Model 

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('CarPrice_Assignment.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
df.shape

(205, 26)

In [4]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
df.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [6]:
df = pd.get_dummies(df)

df.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [7]:
df.shape

(205, 52)

In [8]:
x = df.drop('price', axis=1)

y = df['price']

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2)

In [11]:
model = LinearRegression()

model.fit(xtrain, ytrain)

LinearRegression()

In [12]:
model.score(xtrain, ytrain)

0.9309671734137511

In [13]:
ypred = model.predict(xtest)

ypred

array([ 6532.06741312, 36599.49553086, 10340.03008572,  4928.00921921,
       11577.96205159, 12679.22845478,  4595.5939142 , 18990.59731362,
       38588.44677716, 16219.86817352,  6871.00885364,  6578.30010782,
       34150.14157993,  7976.38850863,  5996.27256826,  8183.68857   ,
        7339.94892343, 26629.69943702,  6922.89758678,  7279.58757387,
       32511.14905555,  7444.13118352, 17721.15691348, 13460.18789754,
       20762.57856505,  5520.86195924,  7171.86024641, 10581.78531582,
       20573.77124321, 14744.01575602, 12179.85686069, 12781.76788406,
       11420.0709494 , 10017.77915095, 17362.09244059, 15640.65198195,
        9275.51853042, 15529.50968143, 13599.08083442, 38679.02223236,
        7714.80909113])

In [14]:
r2_score(ytest, ypred)

0.9320903294437305

## serialize the model using JSON

In [ ]:
y = m1x1 + m2x2 ... + C + e

y = b1x1 + b2x2 ... + b0 + e

In [15]:
model.coef_

array([ 7.00281429e+00, -7.60567750e+01,  7.64328354e+02,  8.63368922e+01,
        5.01418988e+00,  1.08481863e+02, -1.47473155e+03, -4.42942196e+03,
       -7.33848247e+02,  1.04485542e+01,  1.89752229e+00, -1.38131689e+02,
        1.86210488e+02,  3.62981474e+03, -3.62981474e+03, -9.61049226e+02,
        9.61049226e+02, -3.86322573e+02,  3.86322573e+02,  2.54418964e+03,
       -1.76888790e+03, -7.75819650e+02,  7.45398689e+02, -7.44880781e+02,
       -5.70108108e+02, -7.88174827e+01,  6.48925591e+02, -3.95715973e+03,
        3.95715973e+03, -1.97085204e+02,  2.72848411e-12, -3.92330120e+02,
        3.47003807e+03,  1.27988161e+03, -5.63819830e+03,  1.47769394e+03,
        5.41568547e+03, -3.56600277e+03, -3.71588795e+03, -3.60275596e+02,
        5.29135884e+03, -4.54257194e+03,  1.47769394e+03,  7.30708746e+02,
        4.86243126e+02,  1.47769394e+03,  3.62981474e+03, -3.61038441e+03,
        5.82018452e+02, -2.78513525e+03, -5.10959353e+02])

In [16]:
model.intercept_

-34737.687070319975

In [17]:
model_parameters = {}

model_parameters['coef'] = list(model.coef_)
model_parameters['intercept'] = model.intercept_.tolist()

In [19]:
# model_parameters

In [20]:
import json

In [22]:
json_text = json.dumps(model_parameters, indent=4)

# json.dumps -> return a JSON string representing a python object

print(json_text)

{
    "coef": [
        7.002814292293383,
        -76.05677502580467,
        764.3283541963935,
        86.33689222393502,
        5.014189879498218,
        108.48186282840074,
        -1474.731552968005,
        -4429.421959751171,
        -733.8482473067556,
        10.448554227956151,
        1.8975222925146227,
        -138.1316889930522,
        186.21048760701888,
        3629.8147359512664,
        -3629.8147359512623,
        -961.0492257550861,
        961.049225755097,
        -386.32257250583774,
        386.32257250580665,
        2544.1896376835784,
        -1768.8878965285353,
        -775.8196497930193,
        745.3986891956024,
        -744.8807805576143,
        -570.1081080542197,
        -78.8174827007405,
        648.9255907549468,
        -3957.1597299348327,
        3957.1597299348423,
        -197.08520398321076,
        2.7284841053187847e-12,
        -392.3301196718935,
        3470.0380687841657,
        1279.881612403621,
        -5638.198301019618,
     

In [23]:
# save model parameters into a seperate file
# file handling

with open('models/regressor_parameters.txt', 'w') as file:
    file.write(json_text)

### load json model and make predictions

In [24]:
with open('models/regressor_parameters.txt', 'r') as file:
    json_text_loaded = json.load(file)

In [25]:
json_model = LinearRegression()

In [26]:
json_model.coef_ = np.array(json_text_loaded['coef'])
json_model.intercept_ = np.array(json_text_loaded['intercept'])

In [27]:
ypred_json = json_model.predict(xtest)

r2_score(ytest, ypred_json)

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


0.9320903294437305

- the issue with JSON serialization is you need to know what model parameters should be saved

- for complex algorithms where you have a lot of parameters like SVM, RandomForest, 
    than we have to go for pickle or joblib

### serializing ML model using pickle

In [28]:
import pickle

In [29]:
pickle.dump(model, open('models/pickle_model.pkl', 'wb'))  # wb -> write bytestream

In [30]:
# open the pickle model and make the predictions

pickle_model = pickle.load(open('models/pickle_model.pkl', 'rb'))  #rb -> read bytestream

In [31]:
ypred_pickle = pickle_model.predict(xtest)

ypred_pickle

array([ 6532.06741312, 36599.49553086, 10340.03008572,  4928.00921921,
       11577.96205159, 12679.22845478,  4595.5939142 , 18990.59731362,
       38588.44677716, 16219.86817352,  6871.00885364,  6578.30010782,
       34150.14157993,  7976.38850863,  5996.27256826,  8183.68857   ,
        7339.94892343, 26629.69943702,  6922.89758678,  7279.58757387,
       32511.14905555,  7444.13118352, 17721.15691348, 13460.18789754,
       20762.57856505,  5520.86195924,  7171.86024641, 10581.78531582,
       20573.77124321, 14744.01575602, 12179.85686069, 12781.76788406,
       11420.0709494 , 10017.77915095, 17362.09244059, 15640.65198195,
        9275.51853042, 15529.50968143, 13599.08083442, 38679.02223236,
        7714.80909113])

In [32]:
r2_score(ytest, ypred_pickle)

0.9320903294437305

### serialize the ML model using joblib

- better for cases where the python objects hold huge numpy arrays

In [33]:
import joblib

In [34]:
filename = 'models/joblib_model.joblib'

In [35]:
joblib.dump(model, filename)    # bytestream format

['models/joblib_model.joblib']

In [36]:
## open the model file and make the predictions

joblib_model = joblib.load(filename)

ypred_joblib = joblib_model.predict(xtest)

ypred_joblib

array([ 6532.06741312, 36599.49553086, 10340.03008572,  4928.00921921,
       11577.96205159, 12679.22845478,  4595.5939142 , 18990.59731362,
       38588.44677716, 16219.86817352,  6871.00885364,  6578.30010782,
       34150.14157993,  7976.38850863,  5996.27256826,  8183.68857   ,
        7339.94892343, 26629.69943702,  6922.89758678,  7279.58757387,
       32511.14905555,  7444.13118352, 17721.15691348, 13460.18789754,
       20762.57856505,  5520.86195924,  7171.86024641, 10581.78531582,
       20573.77124321, 14744.01575602, 12179.85686069, 12781.76788406,
       11420.0709494 , 10017.77915095, 17362.09244059, 15640.65198195,
        9275.51853042, 15529.50968143, 13599.08083442, 38679.02223236,
        7714.80909113])

In [37]:
r2_score(ytest, ypred_joblib)

0.9320903294437305

Serialization

https://medium.com/@ashaicy/serialization-and-deserialization-techniques-in-python-deserialization-69beed1ed3ef


LLMs Serialization

https://www.reddit.com/r/MachineLearning/comments/15zdxfz/dabout_model_serialization_and_metadata/

In [ ]:
neuron to LLMs

- explain
- math(not in-depth)
- code
- industry key points for decision making
- facts about it